Feature/4.6
t1reless/TaskManager pull request #10
Opened 2022-11-19 10:39 UTC by Froggy-G

2022-11-21 09:35 UTC, aleksandr-semenov-dbp requested changes

2022-11-21 09:35 UTC, aleksandr-semenov-dbp commented on test/test_tag.py
> +        assert response.status_code == HTTPStatus.NO_CONTENT
В delete() мы еще проверяем что элемента не будет например в list()

2022-11-22 12:01 UTC, aleksandr-semenov-dbp requested changes

2022-11-22 12:01 UTC, aleksandr-semenov-dbp commented on test/test_tag.py
> +        assert response.status_code == HTTPStatus.NO_CONTENT
а вот эта проверка не нужна, она уже есть в self.delete()

2022-11-22 16:02 UTC, Froggy-G commented
добавил здесь:

REST_FRAMEWORK = {
...
    'DEFAULT_PERMISSION_CLASSES': ("rest_framework.permissions.IsAuthenticated",),
...
}

чтобы можно было тесты проверять, в новом задании 4.5 решу задание под звездочкой:

"Сделать так, что удалять задачи, статусы и теги может только пользователь с флагом is_staff. Не забудьте написать тесты, чтобы проверить этот кейс. Использование дополнительных пакетов, рекомендованных документацией DRF, приветствуется."

2022-11-24 00:12 UTC, aleksandr-semenov-dbp requested changes

2022-11-24 00:12 UTC, aleksandr-semenov-dbp commented on test/test_tag.py
> +        response = self.unauntificated_request()
мои волки делают auth :) давай напишем это слово чуть пограмотнее (в реальных проектах мы используем линтеры с английскими словарями) и в базовом классе тоже.

2022-11-24 00:12 UTC, aleksandr-semenov-dbp commented on test/test_task.py
> +                    filtered_tasks.append(task)
Это хорошо, но снова придерусь к неймингу - это не filtered_tasks, а наоборот таски которые мы ожидаем что будут филтеред. Лучше для консистентности с остальным что-то типа expected_tasks, так мне было бы понятнее. (ну и с юзерами тоже)

2022-11-24 13:55 UTC, Froggy-G commented on test/test_tag.py
> +        response = self.unauntificated_request()
поправил :)

2022-11-24 13:55 UTC, Froggy-G commented on test/test_task.py
> +                    filtered_tasks.append(task)
исправил

2022-11-27 00:42 UTC, aleksandr-semenov-dbp approved these changes

2022-11-27 13:28 UTC, merged