Feature/4.1
t1reless/TaskManager pull request #5
Opened 2022-10-25 23:44 UTC by Froggy-G

2022-10-26 09:36 UTC, aleksandr-semenov-dbp requested changes

2022-10-26 09:36 UTC, aleksandr-semenov-dbp commented on main/serializers.py
> +            "tags",
Там в задании намекали на вложеные сериализаторы, давай сделаем здесь чтобы тег сериализовался TagSerializer-ом

2022-10-27 21:27 UTC, Froggy-G commented on main/serializers.py
> +            "tags",
@aleksandr-semenov-dbp, упустил этот момент, а как же executor для него не нужно?

2022-10-28 10:03 UTC, Froggy-G commented on main/serializers.py
> +            "tags",
Сделал только tags

2022-10-28 18:38 UTC, aleksandr-semenov-dbp requested changes

2022-10-28 18:38 UTC, aleksandr-semenov-dbp commented on main/serializers.py
> +    tags = TagSerializer()
Тут не один тег, а некоторое их множество

2022-10-28 18:38 UTC, aleksandr-semenov-dbp commented on main/serializers.py
> +            "executor",
Насчет executr-а тоже очень правильная идея сделать вложенный серилизатор

2022-10-29 17:05 UTC, aleksandr-semenov-dbp requested changes

2022-10-29 17:05 UTC, aleksandr-semenov-dbp commented on main/serializers.py
> +    executor = UserSerializer(many=True, read_only=True)
а здесь не нужно many=True

2022-10-30 17:35 UTC, aleksandr-semenov-dbp approved these changes

2022-10-31 02:00 UTC, merged